### ISSUE TITLE
Data requirements

### ISSUE THREAD

**Issue by jiweizhi** [cnaimo/hybrid-ARIMA-LSTM-model#1]
Can you tell me how to get the data of SPDR S&P 500 ETF Trust (SPY)?

**Comment by cnaimo** [comment]
The fastest way would be to download it directly from yahoo finance and then make all of the column names lowercase-> https://finance.yahoo.com/quote/SPY/history?p=SPY

You could also try Alpha Vantage, there is a python library available for their API ->https://github.com/RomelTorres/alpha_vantage
